title: The Fast Track to Julia
baseurl: "/Julia-Cheat-Sheet/"
description: "The Fast Track to Julia - Julia Cheat Sheet"
github_username: JuliaDocs
markdown: kramdown

t:
  en:
    name: "English"
    fast-track: "The Fast Track to"
    quick-dirty: "A quick and dirty overview of"
    github-1: "This page's source is"
    github-2: "located here"
    github-3: "Pull requests are welcome!"
    translate: "Help translate!" # Not used for `en`
  br:
    name: "Português do Brasil"
    fast-track: "A via rápida para"
    quick-dirty: "Uma visão geral ágil e simples para"
    github-1: "O código fonte desta página está"
    github-2: "localizado aqui"
    github-3: "Pull requests são bem-vindos!"
    translate: "Ajude a traduzir!"
  zh-cn:
    name: "中文(简体)"
    fast-track: "快速入门"
    quick-dirty: "一份简单而粗略的语言概览"
    github-1: "页面的源文件放在"
    github-2: "Github 上"
    github-3: "欢迎提交改进！"
    translate: "帮助我们完善翻译!" 
  es:
    name: "Español de España"
    fast-track: "La Via Rápida hacia"
    quick-dirty: "Una aproximación rápida y simple a"
    github-1: "El código fuente de esta página está"
    github-2: "localizado aquí"
    github-3: "¡Los pull requests serán bien recibidos!"
    translate: "¡Ayude con la traducción!"
